theme = "hugo-theme-cactus-plus"
baseURL = "https://renatagerecke.netlify.com/"
languageCode = "en-us"
title = "renata gerecke"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]


[params]
    author = "renata gerecke"
    