---
title: navigating SPSS variables with purrr and stringr - part ii
author: renata gerecke
date: '2019-01-21'
categories:
  - haven
  - purrr
  - rstats
  - spss
  - stringr
tags:
  - haven
  - purrr
  - rstats
  - spss
  - stringr
slug: navigating-spss-variables-with-purrr-and-stringr-part-ii
draft: true
---


## Recap

Last post, I wrote about how we can access SPSS variable metadata using the `attributes()` and `attr()` functions in R; in combination with `purrr:map_chr()` we can easily view variable labels, levels, and more. 

Though the sample data I've created only has 10 variables, often I find myself working with hundreds, and little idea how to find the precise variable names I'm looking for. I've found `stringr:str_extract()` to be particularly powerful in this scenario. 

The data we have asks respondents various combinations of two things: to what degree do you [share/read] on [given social network]. Let's say I want to find the questions which ask about Twitter. I can use the following:

```{r search for twitter}
library(tidyverse)
library(haven)


df <- read_sav("../../static/data/SampleData.sav")

# find_Twitter <- df %>% 
#   map_chr(~attr(., "label")) %>%
#   enframe() %>%
#   filter(str_which(.$value, "Twitter"))
# 
# df %>%
#   select(find_Twitter)

```


We can now see that `q1` and `q6` are the questions which ask about Twitter behavior. 
